# Generated by Django 4.2.1 on 2023-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medseze', '0005_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Jadavpur', 'Jadavpur'), ('Dum Dum', 'Dum Dum'), ('Bidhannagar', 'Bidhannagar'), ('Park circus', 'Park circus'), ('Kalyani', 'Kalyani')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Placed', 'Order Placed'), ('Order Dispatch', 'Order dispatch'), ('Order Delivered', 'Order Delivered')], max_length=50, null=True),
        ),
    ]
