# Generated by Django 4.2.1 on 2023-06-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medseze', '0006_alter_address_city_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[('Nadia', 'Nadia'), ('North 24 parganas', 'North 24 parganas')], max_length=50),
        ),
    ]
