# Generated by Django 4.2.1 on 2023-06-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medseze', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.CharField(max_length=7),
        ),
    ]
